//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItemSearch.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Search.
        /// </summary>
        internal static string CornerIcon_HoverTooltip {
            get {
                return ResourceManager.GetString("CornerIcon_HoverTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building search tree....
        /// </summary>
        internal static string CornerIconLoadingProgress_BuildingSearchTree {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_BuildingSearchTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string CornerIconLoadingProgress_Initial {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading player items from API....
        /// </summary>
        internal static string CornerIconLoadingProgress_PlayerItems {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_PlayerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cached item info....
        /// </summary>
        internal static string CornerIconLoadingProgress_StaticItems {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_StaticItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Armor.
        /// </summary>
        internal static string Filter_Armor_All {
            get {
                return ResourceManager.GetString("Filter_Armor_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        internal static string Filter_Armor_Boots {
            get {
                return ResourceManager.GetString("Filter_Armor_Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat.
        /// </summary>
        internal static string Filter_Armor_Coat {
            get {
                return ResourceManager.GetString("Filter_Armor_Coat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        internal static string Filter_Armor_Gloves {
            get {
                return ResourceManager.GetString("Filter_Armor_Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm.
        /// </summary>
        internal static string Filter_Armor_Helm {
            get {
                return ResourceManager.GetString("Filter_Armor_Helm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm Aquatic.
        /// </summary>
        internal static string Filter_Armor_HelmAquatic {
            get {
                return ResourceManager.GetString("Filter_Armor_HelmAquatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggings.
        /// </summary>
        internal static string Filter_Armor_Leggings {
            get {
                return ResourceManager.GetString("Filter_Armor_Leggings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        internal static string Filter_Armor_Shoulders {
            get {
                return ResourceManager.GetString("Filter_Armor_Shoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Consumables.
        /// </summary>
        internal static string Filter_Consumable_All {
            get {
                return ResourceManager.GetString("Filter_Consumable_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance Change.
        /// </summary>
        internal static string Filter_Consumable_AppearanceChange {
            get {
                return ResourceManager.GetString("Filter_Consumable_AppearanceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booze.
        /// </summary>
        internal static string Filter_Consumable_Booze {
            get {
                return ResourceManager.GetString("Filter_Consumable_Booze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract NPC.
        /// </summary>
        internal static string Filter_Consumable_ContractNpc {
            get {
                return ResourceManager.GetString("Filter_Consumable_ContractNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Filter_Consumable_Currency {
            get {
                return ResourceManager.GetString("Filter_Consumable_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Filter_Consumable_Food {
            get {
                return ResourceManager.GetString("Filter_Consumable_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        internal static string Filter_Consumable_Generic {
            get {
                return ResourceManager.GetString("Filter_Consumable_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween.
        /// </summary>
        internal static string Filter_Consumable_Halloween {
            get {
                return ResourceManager.GetString("Filter_Consumable_Halloween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        internal static string Filter_Consumable_Immediate {
            get {
                return ResourceManager.GetString("Filter_Consumable_Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Random Unlock.
        /// </summary>
        internal static string Filter_Consumable_MountRandomUnlock {
            get {
                return ResourceManager.GetString("Filter_Consumable_MountRandomUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Unlock.
        /// </summary>
        internal static string Filter_Consumable_RandomUnlock {
            get {
                return ResourceManager.GetString("Filter_Consumable_RandomUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport To Friend.
        /// </summary>
        internal static string Filter_Consumable_TeleportToFriend {
            get {
                return ResourceManager.GetString("Filter_Consumable_TeleportToFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmutation.
        /// </summary>
        internal static string Filter_Consumable_Transmutation {
            get {
                return ResourceManager.GetString("Filter_Consumable_Transmutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string Filter_Consumable_Unlock {
            get {
                return ResourceManager.GetString("Filter_Consumable_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Removal.
        /// </summary>
        internal static string Filter_Consumable_UpgradeRemoval {
            get {
                return ResourceManager.GetString("Filter_Consumable_UpgradeRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        internal static string Filter_Consumable_Utility {
            get {
                return ResourceManager.GetString("Filter_Consumable_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Containers.
        /// </summary>
        internal static string Filter_Container_All {
            get {
                return ResourceManager.GetString("Filter_Container_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Filter_Container_Default {
            get {
                return ResourceManager.GetString("Filter_Container_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Box.
        /// </summary>
        internal static string Filter_Container_GiftBox {
            get {
                return ResourceManager.GetString("Filter_Container_GiftBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        internal static string Filter_Container_Immediate {
            get {
                return ResourceManager.GetString("Filter_Container_Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open UI.
        /// </summary>
        internal static string Filter_Container_OpenUI {
            get {
                return ResourceManager.GetString("Filter_Container_OpenUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gathering Tools.
        /// </summary>
        internal static string Filter_Gathering_All {
            get {
                return ResourceManager.GetString("Filter_Gathering_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        internal static string Filter_Gathering_Fishing {
            get {
                return ResourceManager.GetString("Filter_Gathering_Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foraging.
        /// </summary>
        internal static string Filter_Gathering_Foraging {
            get {
                return ResourceManager.GetString("Filter_Gathering_Foraging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Filter_Gathering_Logging {
            get {
                return ResourceManager.GetString("Filter_Gathering_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining.
        /// </summary>
        internal static string Filter_Gathering_Mining {
            get {
                return ResourceManager.GetString("Filter_Gathering_Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gizmos.
        /// </summary>
        internal static string Filter_Gizmo_All {
            get {
                return ResourceManager.GetString("Filter_Gizmo_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Key.
        /// </summary>
        internal static string Filter_Gizmo_ContainerKey {
            get {
                return ResourceManager.GetString("Filter_Gizmo_ContainerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Filter_Gizmo_Default {
            get {
                return ResourceManager.GetString("Filter_Gizmo_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentable Contract NPC.
        /// </summary>
        internal static string Filter_Gizmo_RentableContractNpc {
            get {
                return ResourceManager.GetString("Filter_Gizmo_RentableContractNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited Consumable.
        /// </summary>
        internal static string Filter_Gizmo_UnlimitedConsumable {
            get {
                return ResourceManager.GetString("Filter_Gizmo_UnlimitedConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Items.
        /// </summary>
        internal static string Filter_ItemType_All {
            get {
                return ResourceManager.GetString("Filter_ItemType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string Filter_ItemType_Armor {
            get {
                return ResourceManager.GetString("Filter_ItemType_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Filter_ItemType_Back {
            get {
                return ResourceManager.GetString("Filter_ItemType_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Bag.
        /// </summary>
        internal static string Filter_ItemType_Bag {
            get {
                return ResourceManager.GetString("Filter_ItemType_Bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable.
        /// </summary>
        internal static string Filter_ItemType_Consumable {
            get {
                return ResourceManager.GetString("Filter_ItemType_Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Filter_ItemType_Container {
            get {
                return ResourceManager.GetString("Filter_ItemType_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafting Material.
        /// </summary>
        internal static string Filter_ItemType_CraftingMaterial {
            get {
                return ResourceManager.GetString("Filter_ItemType_CraftingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        internal static string Filter_ItemType_Fishing {
            get {
                return ResourceManager.GetString("Filter_ItemType_Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering.
        /// </summary>
        internal static string Filter_ItemType_Gathering {
            get {
                return ResourceManager.GetString("Filter_ItemType_Gathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizmo.
        /// </summary>
        internal static string Filter_ItemType_Gizmo {
            get {
                return ResourceManager.GetString("Filter_ItemType_Gizmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jade Bot Chip.
        /// </summary>
        internal static string Filter_ItemType_JadeBotChip {
            get {
                return ResourceManager.GetString("Filter_ItemType_JadeBotChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jade Bot Core.
        /// </summary>
        internal static string Filter_ItemType_JadeBotCore {
            get {
                return ResourceManager.GetString("Filter_ItemType_JadeBotCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Filter_ItemType_Key {
            get {
                return ResourceManager.GetString("Filter_ItemType_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minis.
        /// </summary>
        internal static string Filter_ItemType_MiniPet {
            get {
                return ResourceManager.GetString("Filter_ItemType_MiniPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Filter_ItemType_Tool {
            get {
                return ResourceManager.GetString("Filter_ItemType_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait.
        /// </summary>
        internal static string Filter_ItemType_Trait {
            get {
                return ResourceManager.GetString("Filter_ItemType_Trait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinket.
        /// </summary>
        internal static string Filter_ItemType_Trinket {
            get {
                return ResourceManager.GetString("Filter_ItemType_Trinket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy.
        /// </summary>
        internal static string Filter_ItemType_Trophy {
            get {
                return ResourceManager.GetString("Filter_ItemType_Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Component.
        /// </summary>
        internal static string Filter_ItemType_UpgradeComponent {
            get {
                return ResourceManager.GetString("Filter_ItemType_UpgradeComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string Filter_ItemType_Weapon {
            get {
                return ResourceManager.GetString("Filter_ItemType_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rarities.
        /// </summary>
        internal static string Filter_Rarity_All {
            get {
                return ResourceManager.GetString("Filter_Rarity_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascended.
        /// </summary>
        internal static string Filter_Rarity_Ascended {
            get {
                return ResourceManager.GetString("Filter_Rarity_Ascended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Filter_Rarity_Basic {
            get {
                return ResourceManager.GetString("Filter_Rarity_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic.
        /// </summary>
        internal static string Filter_Rarity_Exotic {
            get {
                return ResourceManager.GetString("Filter_Rarity_Exotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        internal static string Filter_Rarity_Fine {
            get {
                return ResourceManager.GetString("Filter_Rarity_Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk.
        /// </summary>
        internal static string Filter_Rarity_Junk {
            get {
                return ResourceManager.GetString("Filter_Rarity_Junk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        internal static string Filter_Rarity_Legendary {
            get {
                return ResourceManager.GetString("Filter_Rarity_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterwork.
        /// </summary>
        internal static string Filter_Rarity_Masterwork {
            get {
                return ResourceManager.GetString("Filter_Rarity_Masterwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Filter_Rarity_Rare {
            get {
                return ResourceManager.GetString("Filter_Rarity_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory.
        /// </summary>
        internal static string Filter_Trinket_Accessory {
            get {
                return ResourceManager.GetString("Filter_Trinket_Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Trinkets.
        /// </summary>
        internal static string Filter_Trinket_All {
            get {
                return ResourceManager.GetString("Filter_Trinket_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        internal static string Filter_Trinket_Amulet {
            get {
                return ResourceManager.GetString("Filter_Trinket_Amulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string Filter_Trinket_Ring {
            get {
                return ResourceManager.GetString("Filter_Trinket_Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Upgrade Components.
        /// </summary>
        internal static string Filter_UpgradeComponent_All {
            get {
                return ResourceManager.GetString("Filter_UpgradeComponent_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Filter_UpgradeComponent_Default {
            get {
                return ResourceManager.GetString("Filter_UpgradeComponent_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem.
        /// </summary>
        internal static string Filter_UpgradeComponent_Gem {
            get {
                return ResourceManager.GetString("Filter_UpgradeComponent_Gem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune.
        /// </summary>
        internal static string Filter_UpgradeComponent_Rune {
            get {
                return ResourceManager.GetString("Filter_UpgradeComponent_Rune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigil.
        /// </summary>
        internal static string Filter_UpgradeComponent_Sigil {
            get {
                return ResourceManager.GetString("Filter_UpgradeComponent_Sigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Weapons.
        /// </summary>
        internal static string Filter_Weapon_All {
            get {
                return ResourceManager.GetString("Filter_Weapon_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        internal static string Filter_Weapon_Axe {
            get {
                return ResourceManager.GetString("Filter_Weapon_Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        internal static string Filter_Weapon_Dagger {
            get {
                return ResourceManager.GetString("Filter_Weapon_Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        internal static string Filter_Weapon_Focus {
            get {
                return ResourceManager.GetString("Filter_Weapon_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatsword.
        /// </summary>
        internal static string Filter_Weapon_Greatsword {
            get {
                return ResourceManager.GetString("Filter_Weapon_Greatsword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        internal static string Filter_Weapon_Hammer {
            get {
                return ResourceManager.GetString("Filter_Weapon_Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harpoon.
        /// </summary>
        internal static string Filter_Weapon_Harpoon {
            get {
                return ResourceManager.GetString("Filter_Weapon_Harpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Bundle.
        /// </summary>
        internal static string Filter_Weapon_LargeBundle {
            get {
                return ResourceManager.GetString("Filter_Weapon_LargeBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Bow.
        /// </summary>
        internal static string Filter_Weapon_LongBow {
            get {
                return ResourceManager.GetString("Filter_Weapon_LongBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mace.
        /// </summary>
        internal static string Filter_Weapon_Mace {
            get {
                return ResourceManager.GetString("Filter_Weapon_Mace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        internal static string Filter_Weapon_Pistol {
            get {
                return ResourceManager.GetString("Filter_Weapon_Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifle.
        /// </summary>
        internal static string Filter_Weapon_Rifle {
            get {
                return ResourceManager.GetString("Filter_Weapon_Rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scepter.
        /// </summary>
        internal static string Filter_Weapon_Scepter {
            get {
                return ResourceManager.GetString("Filter_Weapon_Scepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string Filter_Weapon_Shield {
            get {
                return ResourceManager.GetString("Filter_Weapon_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Bow.
        /// </summary>
        internal static string Filter_Weapon_ShortBow {
            get {
                return ResourceManager.GetString("Filter_Weapon_ShortBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Bundle.
        /// </summary>
        internal static string Filter_Weapon_SmallBundle {
            get {
                return ResourceManager.GetString("Filter_Weapon_SmallBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speargun.
        /// </summary>
        internal static string Filter_Weapon_Speargun {
            get {
                return ResourceManager.GetString("Filter_Weapon_Speargun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Filter_Weapon_Staff {
            get {
                return ResourceManager.GetString("Filter_Weapon_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        internal static string Filter_Weapon_Sword {
            get {
                return ResourceManager.GetString("Filter_Weapon_Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torch.
        /// </summary>
        internal static string Filter_Weapon_Torch {
            get {
                return ResourceManager.GetString("Filter_Weapon_Torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toy.
        /// </summary>
        internal static string Filter_Weapon_Toy {
            get {
                return ResourceManager.GetString("Filter_Weapon_Toy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toy Two-Handed.
        /// </summary>
        internal static string Filter_Weapon_ToyTwoHanded {
            get {
                return ResourceManager.GetString("Filter_Weapon_ToyTwoHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trident.
        /// </summary>
        internal static string Filter_Weapon_Trident {
            get {
                return ResourceManager.GetString("Filter_Weapon_Trident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhorn.
        /// </summary>
        internal static string Filter_Weapon_Warhorn {
            get {
                return ResourceManager.GetString("Filter_Weapon_Warhorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string FilterPanel_Clear {
            get {
                return ResourceManager.GetString("FilterPanel_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string ItemTooltip_CharacterEquipment {
            get {
                return ResourceManager.GetString("ItemTooltip_CharacterEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string ItemTooltip_CharacterInventory {
            get {
                return ResourceManager.GetString("ItemTooltip_CharacterInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contained in: .
        /// </summary>
        internal static string ItemTooltip_ContainedIn {
            get {
                return ResourceManager.GetString("ItemTooltip_ContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item .
        /// </summary>
        internal static string ItemTooltip_FallbackTextPrefix {
            get {
                return ResourceManager.GetString("ItemTooltip_FallbackTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        internal static string ItemTooltip_Location {
            get {
                return ResourceManager.GetString("ItemTooltip_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tab {0}.
        /// </summary>
        internal static string ItemTooltip_Tab {
            get {
                return ResourceManager.GetString("ItemTooltip_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmuted to: .
        /// </summary>
        internal static string ItemTooltip_Transmuted {
            get {
                return ResourceManager.GetString("ItemTooltip_Transmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string ResultTitle_Bank {
            get {
                return ResourceManager.GetString("ResultTitle_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character: .
        /// </summary>
        internal static string ResultTitle_Character {
            get {
                return ResourceManager.GetString("ResultTitle_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Storage.
        /// </summary>
        internal static string ResultTitle_Materials {
            get {
                return ResourceManager.GetString("ResultTitle_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ResultTitle_Other {
            get {
                return ResourceManager.GetString("ResultTitle_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Inventory.
        /// </summary>
        internal static string ResultTitle_SharedInventory {
            get {
                return ResourceManager.GetString("ResultTitle_SharedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Post Delivery Box.
        /// </summary>
        internal static string ResultTitle_TPDeliveryBox {
            get {
                return ResourceManager.GetString("ResultTitle_TPDeliveryBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Post Sell Order.
        /// </summary>
        internal static string ResultTitle_TPSellOrder {
            get {
                return ResourceManager.GetString("ResultTitle_TPSellOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchWindow_MainSubtitle {
            get {
                return ResourceManager.GetString("SearchWindow_MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchWindow_SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchWindow_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Search.
        /// </summary>
        internal static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This includes mostly equipment from the legendary armory. Includes account-bound legendary armor, weapons, trinkets, and upgrade components..
        /// </summary>
        internal static string Settings_HideLegendaryArmory_Description {
            get {
                return ResourceManager.GetString("Settings_HideLegendaryArmory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide account-bound legendary equipment.
        /// </summary>
        internal static string Settings_HideLegendaryArmory_Name {
            get {
                return ResourceManager.GetString("Settings_HideLegendaryArmory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to refresh your items from the GW2 API. Range is from 3 - 33 Minutes.
        /// </summary>
        internal static string Settings_PlayerDataRefreshIntervalMinutes_Description {
            get {
                return ResourceManager.GetString("Settings_PlayerDataRefreshIntervalMinutes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Refresh Interval.
        /// </summary>
        internal static string Settings_PlayerDataRefreshIntervalMinutes_Name {
            get {
                return ResourceManager.GetString("Settings_PlayerDataRefreshIntervalMinutes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How item icons are cached. \nFile: icons are cached as files on disk. \nMemory: icons are cached in memory. Each time Blishhud restarts the cache will be cleared. \nNone: No caching..
        /// </summary>
        internal static string Settings_RenderCacheMethod_Description {
            get {
                return ResourceManager.GetString("Settings_RenderCacheMethod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Icon Cache.
        /// </summary>
        internal static string Settings_RenderCacheMethod_Name {
            get {
                return ResourceManager.GetString("Settings_RenderCacheMethod_Name", resourceCulture);
            }
        }
    }
}
