//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItemSearch.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building search tree....
        /// </summary>
        internal static string CornerIconLoadingProgress_BuildingSearchTree {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_BuildingSearchTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string CornerIconLoadingProgress_Initial {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading player items from API....
        /// </summary>
        internal static string CornerIconLoadingProgress_PlayerItems {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_PlayerItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cached item info....
        /// </summary>
        internal static string CornerIconLoadingProgress_StaticItems {
            get {
                return ResourceManager.GetString("CornerIconLoadingProgress_StaticItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string ItemTooltip_CharacterEquipment {
            get {
                return ResourceManager.GetString("ItemTooltip_CharacterEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string ItemTooltip_CharacterInventory {
            get {
                return ResourceManager.GetString("ItemTooltip_CharacterInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contained in: .
        /// </summary>
        internal static string ItemTooltip_ContainedIn {
            get {
                return ResourceManager.GetString("ItemTooltip_ContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item .
        /// </summary>
        internal static string ItemTooltip_FallbackTextPrefix {
            get {
                return ResourceManager.GetString("ItemTooltip_FallbackTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        internal static string ItemTooltip_Location {
            get {
                return ResourceManager.GetString("ItemTooltip_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tab {0}.
        /// </summary>
        internal static string ItemTooltip_Tab {
            get {
                return ResourceManager.GetString("ItemTooltip_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string ResultTitle_Bank {
            get {
                return ResourceManager.GetString("ResultTitle_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character: .
        /// </summary>
        internal static string ResultTitle_Character {
            get {
                return ResourceManager.GetString("ResultTitle_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Storage.
        /// </summary>
        internal static string ResultTitle_Materials {
            get {
                return ResourceManager.GetString("ResultTitle_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ResultTitle_Other {
            get {
                return ResourceManager.GetString("ResultTitle_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Inventory.
        /// </summary>
        internal static string ResultTitle_SharedInventory {
            get {
                return ResourceManager.GetString("ResultTitle_SharedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Post Delivery Box.
        /// </summary>
        internal static string ResultTitle_TPDeliveryBox {
            get {
                return ResourceManager.GetString("ResultTitle_TPDeliveryBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Post Sell Order.
        /// </summary>
        internal static string ResultTitle_TPSellOrder {
            get {
                return ResourceManager.GetString("ResultTitle_TPSellOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchWindow_MainSubtitle {
            get {
                return ResourceManager.GetString("SearchWindow_MainSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchWindow_SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchWindow_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Search.
        /// </summary>
        internal static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to refresh your items from the GW2 API. Note that the API data is already delayed by a few minutes..
        /// </summary>
        internal static string Settings_PlayerDataRefreshIntervalMinutes_Description {
            get {
                return ResourceManager.GetString("Settings_PlayerDataRefreshIntervalMinutes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Refresh Interval (Minutes).
        /// </summary>
        internal static string Settings_PlayerDataRefreshIntervalMinutes_Name {
            get {
                return ResourceManager.GetString("Settings_PlayerDataRefreshIntervalMinutes_Name", resourceCulture);
            }
        }
    }
}
